sudo: true

language: python
python: 3.5

install:
- cd ~/build/HMProgrammingClub/NYCSL2/backend
- ./install.sh

script:
- cd ~/build/HMProgrammingClub/NYCSL2/
- echo "[BACKEND]\nsecretKey = random_secret_key\nsalt = random_salt" | tee nycsl.ini
- cd backend
- ./runTests.sh

notifications:
  slack: frclions:812VES7Q5XzGvrcSmquYMwrF
