sudo: true

language: python
python: 3.5

before_install:
- sudo apt-get install -qq mongodb-server
- sudo mkdir -p /data/db
- sudo chown `id -u` /data/db

install:
- cd backend
- pip install flask flask-restful pymongo
- cd ..

script:
- cd backend
- python3 tests.py

notifications:
  slack: frclions:812VES7Q5XzGvrcSmquYMwrF
