sudo: true

language: python
python:
- "3.4"

install:
- cd ~/build/HMProgrammingClub/NYCSL2/backend
- ./install.sh
- sudo mkdir -p /data/db/

script:
- cd ~/build/HMProgrammingClub/NYCSL2/
- echo "[BACKEND]" >> nycsl.ini
- echo "secretKey = random_secret_key" >> nycsl.ini
- echo "salt = random_salt" >> nycsl.ini
- cd backend
- ./runTests.sh

notifications:
  slack: frclions:812VES7Q5XzGvrcSmquYMwrF
