sudo: required

dist: trusty

language: generic

install:
- cd ~/build/HMProgrammingClub/NYCSL2/backend
- sudo ./install.sh
- sudo mkdir -p /data/db/

script:
- cd ~/build/HMProgrammingClub/NYCSL2/
- cp travis.ini nycsl.ini
- cd backend
- sudo ./runTests.sh

notifications:
  slack: frclions:812VES7Q5XzGvrcSmquYMwrF
